name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: zip -r text-zebar.zip build/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: text-zebar.zip
